GET http://localhost:3000/api/current
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6MSwiQXV0aG9yaXplZCI6dHJ1ZSwiRGF0YSI6eyJOYW1lIjoiWmV6aW4iLCJSb2xlIjoiQWRtaW4ifSwiZXhwIjoxNzA5ODI2NjY2fQ.uVv8f7BdwYDr40xFPPqovhv0vxlb7203WyNiIhGrANo
```